{% set name = "wsidata" %}
{% set version = "0.7.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wsidata-{{ version }}.tar.gz
  sha256: 733882195d51f422fe0ea3571f15fefcf45d6d35e9fa3bbe0ed0b058856c3948
  patches:
    - openslide.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - spatialdata >=0.3.0
    - opencv
    - openslide-python >=1.4.1
    - tiffslide
    - rich
    - pytorch >=2.0.0

test:
  imports:
    - wsidata
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/rendeirolab/wsidata
  summary: Data structures and I/O functions for whole-slide image (WSI).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Mr-Milk
    - sarthakpati
