{% set name = "wsidata" %}
{% set version = "0.11.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/wsidata-{{ version }}.tar.gz
  sha256: e48521251a92372f7323e246dbb064924e28dd6620235c201b7ca66f274f7bc1
  patches:
    - openslide.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - spatialdata >=0.6.0
    - opencv
    - openslide-python >=1.4.1
    - rich
    - pytorch >=2.0.0
    - zarr >=3.0

test:
  imports:
    - wsidata
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/rendeirolab/wsidata
  summary: Data structures and I/O functions for whole-slide image (WSI).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Mr-Milk
    - sarthakpati
