{% set name = "wsidata" %}
{% set version = "0.7.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wsidata-{{ version }}.tar.gz
  sha256: 935f1c51e1e2f1d0aa52d286019c24b8a869d621c2618db80b60526ef10a7e03
  patches:
    - openslide.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - spatialdata >=0.3.0
    - opencv
    - openslide-python >=1.4.1
    - tiffslide
    - rich
    - pytorch >=2.0.0

test:
  imports:
    - wsidata
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/rendeirolab/wsidata
  summary: Data structures and I/O functions for whole-slide image (WSI).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Mr-Milk
    - sarthakpati
