{% set name = "wsidata" %}
{% set version = "0.8.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wsidata-{{ version }}.tar.gz
  sha256: a19db07f6974b8032d5a4643599ca7015175d537ef88a39031090a88aefe1e55
  patches:
    - openslide.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - spatialdata >=0.6.0
    - opencv
    - openslide-python >=1.4.1
    - tifffile <2025.5.21,>=2023.7.4
    - rich
    - pytorch >=2.0.0
    - zarr <3.0,>=2.16.0
    - tiffslide <=2.4.0

test:
  imports:
    - wsidata
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/rendeirolab/wsidata
  summary: Data structures and I/O functions for whole-slide image (WSI).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Mr-Milk
    - sarthakpati
